drop table if exists users, requests, items, comments, bookings;

create table if not exists users
(
    id    BIGINT generated by default as identity not null,
    name  VARCHAR(50)                             not null,
    email VARCHAR(50)                             not null,
    constraint UQ_USER_EMAIL unique (email),
    constraint pk_user primary key (id)
);

create table if not exists requests
(
    id           BIGINT generated by default as identity not null,
    description  VARCHAR(1000)                           not null,
    requester_id BIGINT references users (id) on delete cascade,
    created      TIMESTAMP WITHOUT TIME ZONE,
    constraint pk_request primary key (id)
);

create table if not exists items
(
    id           BIGINT generated by default as identity        not null,
    name         VARCHAR(50)                                    not null,
    description  VARCHAR(1000)                                  not null,
    is_available BOOLEAN,
    id_owner     BIGINT references users (id) on delete cascade not null,
    request_id   BIGINT references requests (id) on delete cascade,
    constraint pk_item primary key (id)
);

create table if not exists comments
(
    id        BIGINT generated by default as identity        not null,
    text      VARCHAR(1000)                                  not null,
    item_id   BIGINT references items (id) on delete cascade not null,
    author_id BIGINT references users (id) on delete cascade not null,
    created   TIMESTAMP WITHOUT TIME ZONE,
    constraint pk_comments primary key (id)
);

create table if not exists bookings
(
    id         BIGINT generated by default as identity        not null,
    start_date TIMESTAMP WITHOUT TIME ZONE                    not null,
    end_date   TIMESTAMP WITHOUT TIME ZONE                    not null,
    item_id    BIGINT references items (id) on delete cascade not null,
    booker_id  BIGINT references users (id) on delete cascade not null,
    status     VARCHAR(10),
    constraint pk_booking primary key (id)
);